# Generated by Django 4.0.3 on 2022-09-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
